version: "3.9"
services: 
  web: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "4201:4201"
    volumes: 
      - ./:/app
    depends_on: 
      - db
    environment:
      # <dialect>://<user>:<user_password>@<database_address>:<port>/<database_name>
      DB_CONNECTION_STRING: "postgres://postgres:password@db:5432/postgres"
  db:
    image: postgres:latest
    ports: 
      - "5432:5432" 
    environment: 
      POSTGRES_PASSWORD: password