version: "3.9"
services: 
  web: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "4201:4201"
    volumes: 
      - .:/app
    depends_on: 
      - db
    environment:
      DB_CONNECTION_STRING: "postgres://postgres:password@db:5432/postgres"
    stdin_open: true
    tty: true   
  db:
    image: postgres:latest
    ports: 
      - "5432:5432" 
    environment: 
      POSTGRES_PASSWORD: password
    volumes:
      - ./local_data:/var/lib/postgresql/data