version: "3.9"
services: 
  db:
    image: postgres:latest
    ports: 
      - "5432:5432" 
    environment: 
      POSTGRES_PASSWORD: password
    volumes:
      - syscpe_db:/var/lib/postgresql/data

volumes:
  syscpe_db:
    external: true