version: "3.9"
services: 
  web: 
    build: 
      context: ..
      dockerfile: deploy/server.local.dockerfile
    ports: 
      - "4000:4000"
    volumes: 
      - ..:/app
    tty: true
    stdin_open: true