version: "3.9"
services: 
  runner:
    build: 
      context: ..
      dockerfile: deploy/tests-runner.dockerfile
    environment:
      DB_USER: test_user
      DB_DATABASE: test_postgres
      DB_PASSWORD: test_password
    entrypoint: ["npm", "run", "integration-test"]
    stdin_open: true
    tty: true