name: Run lint and tests
'on': push
jobs:
  run_lint_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: "Install dependencies"
        run: cd frontend && npm install
      - name: "Run lint"
        run: cd frontend && npm run lint
      - name: "Run tests"
        run: cd frontend && npm run test -- --watchAll=false
          
